language: node_js
node_js: "12"
script: npm run test
before_deploy: npm run build
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    branch: main
notifications:
  webhooks: https://coveralls.io/webhook